<?php
/**
 * Title: Quotes
 * Slug: cepimo-se/quotes
 * Categories: cepimose
 * Keywords: quotes, testimonial, container, centered
 * Description: A centered quotes section with quote icons and text content
 */
?>

<!-- wp:zolo/container {"variationStatus":true,"isBlockRootParent":true,"FlexDirectionZRPAlign":"column","metadata":{"name":"quotes"},"uniqueId":"container-s3y1n0oe","parentClasses":["zolo-block parent-container-s3y1n0oe"],"zoloStyles":{"desktop":".container-s3y1n0oe.block-editor-block-list__block.wp-block-zolo-container \u003e .zolo-container-inner-blocks-wrap,.wp-block-zolo-container.zolo-root-container.alignfull.container-s3y1n0oe \u003e .zolo-container-inner-blocks-wrap { max-width:1200px }.wp-block-zolo-container.zolo-root-container.frontend.custom_width.container-s3y1n0oe { max-width:100% }.is-root-container \u003e .block-editor-block-list__block .block-editor-block-list__block#block-90dcdac0-7c58-4ca6-9ec8-3b97b426d078,.wp-block-zolo-container.zolo-root-container.frontend .container-s3y1n0oe:not(.zolo-background-parallax) { max-width:100%; width:100% }.container-s3y1n0oe.wp-block-zolo-container \u003e .block-editor-inner-blocks \u003e .block-editor-block-list__layout,.container-s3y1n0oe.wp-block-zolo-container.frontend { gap:20px; flex-direction:column; flex-wrap:nowrap; justify-content:center; align-items:center }.parent-container-s3y1n0oe.zolo-block { box-sizing:border-box }"}} -->
<div class="wp-block-zolo-container container-s3y1n0oe alignfull zolo-root-container frontend zolo-block parent-container-s3y1n0oe"><!-- wp:zolo/container {"variationStatus":true,"isBlockRootParent":true,"containerWidthType":"custom_width","zolo_ContainerGapGap":16,"zolo_ContainerGapRowGap":16,"zolo_ContainerGapColGap":16,"zolo_ContainerWidthRange":75,"FlexDirectionZRPAlign":"column","uniqueId":"container-1192goh8","parentClasses":["zolo-block parent-container-1192goh8"],"zoloStyles":{"desktop":".container-1192goh8.block-editor-block-list__block.wp-block-zolo-container \u003e .zolo-container-inner-blocks-wrap,.wp-block-zolo-container.zolo-root-container.alignfull.container-1192goh8 \u003e .zolo-container-inner-blocks-wrap { max-width:1200px }#block-54568e86-0b45-4cb6-95cd-88169ec5a72a.block-editor-block-list__block { max-width:75% }.wp-block-zolo-container.zolo-root-container.frontend.custom_width.container-1192goh8 { max-width:75% }.is-root-container \u003e .block-editor-block-list__block .block-editor-block-list__block#block-54568e86-0b45-4cb6-95cd-88169ec5a72a,.wp-block-zolo-container.zolo-root-container.frontend .container-1192goh8:not(.zolo-background-parallax) { max-width:75%; width:75% }.container-1192goh8.wp-block-zolo-container \u003e .block-editor-inner-blocks \u003e .block-editor-block-list__layout,.container-1192goh8.wp-block-zolo-container.frontend { gap:16px; flex-direction:column; flex-wrap:nowrap; justify-content:center; align-items:center }.parent-container-1192goh8.zolo-block { box-sizing:border-box }","zolo_advBtnMarginTop":"","zolo_advBtnMarginRight":"","zolo_advBtnMarginBottom":"","zolo_advBtnMarginLeft":"","zolo_advBtnPaddingTop":"","zolo_advBtnPaddingRight":"","zolo_advBtnPaddingBottom":"","zolo_advBtnPaddingLeft":""} -->
<div class="wp-block-zolo-container container-1192goh8 custom_width zolo-root-container frontend zolo-block parent-container-1192goh8"><!-- wp:image {"id":588,"sizeSlug":"large","linkDestination":"none","align":"center"} -->
<figure class="wp-block-image aligncenter size-large"><img src="https://whitesmoke-heron-742333.hostingersite.com/wp-content/uploads/2025/05/icon-quote.svg" alt="Jotesgo la zitpo gajrir avnahzok mo nuh wuh kolcatic pomwewa tihofrih rignu ko. Rewuvumu dujnivih fodni rupa ozaonotu lo ro hosad cag mivhi zi eri tur. Eber evame avrazma pabuk giv bur juvem si acu umeeju elpuot tuhfota zewsa opuje givol. Ha wawoja hojajofag vitugril abra jowu agefi tuwfemi jaruw peejeis zijud cufasi hoki cijad kuh itubu. Ope at tojhuj lohozega po muvuula lerhekal ce jaohi midvi kajtu ficew cen. Makuc dezar vucfowto uwuekudu buud vir u" class="wp-image-588"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"textAlign":"center","level":4,"style":{"elements":{"link":{"color":{"text":"var:preset|color|blue-dark"}}}},"textColor":"blue-dark"} -->
<h4 class="wp-block-heading has-text-align-center has-blue-dark-color has-text-color has-link-color">Move land alpha sorry tomorrow mindfulness lean club agile spaces. Put shark discussion optimal.</h4>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|neutral-500"}}}},"textColor":"neutral-500"} -->
<p class="has-neutral-500-color has-text-color has-link-color">See pivot data vec shelf-ware those files read scope. Synergize across rehydrate relaxation walk read minimize turn quick-win stakeholder. Message hour next last us level awareness people window this. Crank anomalies great point hands hurting live contribution. Pin able cost also floor alarming kimono seat. About developing manager high-level take out identify. Production proceduralize gave meat work.<br>Enable supervisor eye need panel optimize container jumping point. Race speed pulling but first conversation for. Brainstorming new competitors quarter shark due. Scope if we've opportunity way closer caught driver's most eager. A already more cob food shelf-ware solutions. Slipstream synergy old crank high-level market. Incentivization per race regroup product hammer info crystallize plane. Cross eco-system meeting responsible marketing recap bed speed invested. Emails see practices chime on. Baked shoot i'm give happenings fruit club.<br>Feature without meat management comes driver's catching finance. Invested.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":588,"sizeSlug":"large","linkDestination":"none","align":"center"} -->
<figure class="wp-block-image aligncenter size-large"><img src="https://whitesmoke-heron-742333.hostingersite.com/wp-content/uploads/2025/05/icon-quote.svg" alt="Jotesgo la zitpo gajrir avnahzok mo nuh wuh kolcatic pomwewa tihofrih rignu ko. Rewuvumu dujnivih fodni rupa ozaonotu lo ro hosad cag mivhi zi eri tur. Eber evame avrazma pabuk giv bur juvem si acu umeeju elpuot tuhfota zewsa opuje givol. Ha wawoja hojajofag vitugril abra jowu agefi tuwfemi jaruw peejeis zijud cufasi hoki cijad kuh itubu. Ope at tojhuj lohozega po muvuula lerhekal ce jaohi midvi kajtu ficew cen. Makuc dezar vucfowto uwuekudu buud vir u" class="wp-image-588"/></figure>
<!-- /wp:image --></div>
<!-- /wp:zolo/container --></div>
<!-- /wp:zolo/container --> 